In [1]:
#PART 2
#Have Customers Narrow Their Travel Searches Based on Temperature and Precipitation

In [2]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
%matplotlib inline
# Import the API key.
from config import g_key

In [3]:
#2 # 2. Read and load the cities database
city_data_df = pd.read_csv("weather_data/WeatherPy_challenge.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Weather Description,Rain in inches (last 3 hrs),Snow in inches (last 3 hrs)
0,0,Provideniya,64.38,-173.30,-8.21,88,0,13.87,RU,2020-03-01 18:16:30,clear sky,0.0,0.0
1,1,Belyy Yar,53.60,91.39,14.00,92,8,2.24,RU,2020-03-01 18:16:30,clear sky,0.0,0.0
2,2,Siwana,25.63,72.42,72.95,32,0,9.40,IN,2020-03-01 18:16:30,clear sky,0.0,0.0
3,3,Bluff,-46.60,168.33,51.01,93,56,4.56,NZ,2020-03-01 18:13:32,broken clouds,0.0,0.0
4,4,Dingle,11.00,122.67,72.41,85,0,11.39,PH,2020-03-01 18:16:31,clear sky,0.0,0.0

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
#3.Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

#Ask the customer if he or she would like it to be raining or not?
rain = input("Do you want it to be raining? (yes/no) ")

#Ask the customer if he or she would like it to be snowing or not?
snow = input("Do you want it to be snowing? (yes/no) ")

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) yes
Do you want it to be snowing? (yes/no) no

In [6]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df['Max Temp'] <= max_temp) & \
                                       (city_data_df['Max Temp'] >= min_temp)]
#preferred_cities_df.head(10)
    
if (rain == 'yes') | (rain == 'Yes') | (rain == 'YES'):
    preferred_cities_rain_df = preferred_cities_df.loc[(preferred_cities_df['Rain in inches (last 3 hrs)'] > 0)]
else:
    preferred_cities_rain_df = preferred_cities_df.loc[(preferred_cities_df['Rain in inches (last 3 hrs)'] == 0)]

if (snow == 'yes') | (snow == 'Yes') | (snow == 'YES'):
    preferred_cities_snow_df = preferred_cities_df.loc[(preferred_cities_df['Snow in inches (last 3 hrs)'] > 0)]
else:
    preferred_cities_snow_df = preferred_cities_df.loc[(preferred_cities_df['Snow in inches (last 3 hrs)'] == 0)]

#preferred_cities_snow_df

preferred_cities_rain_snow_df = [preferred_cities_rain_df, preferred_cities_snow_df]

preferred_cities_all_df = pd.concat(preferred_cities_rain_snow_df)
preferred_cities_all_df = preferred_cities_all_df.drop_duplicates()
preferred_cities_all_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Weather Description,Rain in inches (last 3 hrs),Snow in inches (last 3 hrs)
20,20,Rikitea,-23.12,-134.97,80.19,80,100,12.10,PF,2020-03-01 18:16:34,light rain,1.69,0.0
76,76,Riachao,-7.36,-46.62,89.13,55,15,2.95,BR,2020-03-01 18:16:45,light rain,0.25,0.0
81,81,Kavieng,-2.57,150.80,83.70,72,43,1.41,PG,2020-03-01 18:16:46,moderate rain,4.31,0.0
89,89,Castro,-24.79,-50.01,71.35,83,19,3.60,BR,2020-03-01 18:16:49,light rain,2.38,0.0
102,102,San Policarpo,12.18,125.51,76.86,81,9,9.42,PH,2020-03-01 18:16:52,light rain,0.13,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,573,Victoria,22.29,114.16,73.00,78,19,2.24,HK,2020-03-01 18:13:40,few clouds,0.00,0.0
581,581,Chicama,-7.84,-79.15,75.20,78,90,9.17,PE,2020-03-01 18:18:21,overcast clouds,0.00,0.0
583,583,Soyo,-6.13,12.37,84.20,74,86,5.82,AO,2020-03-01 18:18:22,overcast clouds,0.00,0.0
588,588,Salalah,17.02,54.09,77.00,73,75,4.70,OM,2020-03-01 18:18:22,broken clouds,0.00,0.0
595,595,Jieshi,22.81,115.83,72.00,72,26,1.01,CN,2020-03-01 18:18:24,scattered clouds,0.00,0.0

In [7]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_all_df[["City", "Country", "Max Temp","Weather Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
20,Rikitea,PF,80.19,light rain,-23.12,-134.97,
76,Riachao,BR,89.13,light rain,-7.36,-46.62,
81,Kavieng,PG,83.70,moderate rain,-2.57,150.80,
89,Castro,BR,71.35,light rain,-24.79,-50.01,
102,San Policarpo,PH,76.86,light rain,12.18,125.51,
...,...,...,...,...,...,...,...
573,Victoria,HK,73.00,few clouds,22.29,114.16,
581,Chicama,PE,75.20,overcast clouds,-7.84,-79.15,
583,Soyo,AO,84.20,overcast clouds,-6.13,12.37,
588,Salalah,OM,77.00,broken clouds,17.02,54.09,
595,Jieshi,CN,72.00,scattered clouds,22.81,115.83,

In [8]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [9]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
   # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        pass

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
hotel_df.head()

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
20,Rikitea,PF,80.19,light rain,-23.12,-134.97,Pension Maro'i
76,Riachao,BR,89.13,light rain,-7.36,-46.62,Hotel Universal
81,Kavieng,PG,83.70,moderate rain,-2.57,150.80,Nusa Island Retreat
89,Castro,BR,71.35,light rain,-24.79,-50.01,CHACARA BAILLY
102,San Policarpo,PH,76.86,light rain,12.18,125.51,Zal-Ann Beach Resort

In [11]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt></dt><dd>{Max Temp} °F</dd>
#</dl>Weather</dt><dd>{Weather Description} and {Max Temp}°F</dd>
<dt>Weather</dt><dd>{Weather Description} and {Max Temp} °F</dd>
</dl>
"""

In [15]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [16]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# 5. Save and upload the new Dataframe
outfile = "weather_data/WeatherPy_vacation.csv"
hotel_df.to_csv(outfile, index_label="City_ID")